### ISSUE TITLE
OEO viewer installation raises dependency errors

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1292]
## Description of the issue

When I follow the i[nstallation instructions](https://github.com/OpenEnergyPlatform/oeplatform#3-setup-the-oeo-viewer) in the readme to install the oeo-viewer, I have to fight my way through some incompatibilities in the dependencies. Is there a better solution here?

## Steps to Reproduce
1. node/npm is installed
2. navigate to the oeo-viewer app and run `npm install`

Output:
``` bash
github\oeplatform\oeo_viewer\client>npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-event-listener@0.6.6
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   react@"^17.0.2" from the root project
npm WARN   30 more (@fluentui/react-component-event-listener, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.3.0" from react-event-listener@0.6.6
npm WARN node_modules/react-event-listener
npm WARN   react-event-listener@"^0.6.0" from react-swipeable-views-utils@0.13.9
npm WARN   node_modules/react-swipeable-views-utils
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.3.0" from react-event-listener@0.6.6
npm WARN   node_modules/react-event-listener
npm WARN     react-event-listener@"^0.6.0" from react-swipeable-views-utils@0.13.9
npm WARN     node_modules/react-swipeable-views-utils
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-native@0.70.2
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   react@"^17.0.2" from the root project
npm WARN   30 more (@fluentui/react-component-event-listener, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"18.1.0" from react-native@0.70.2
npm WARN node_modules/react-native
npm WARN   peer react-native@">=0.58" from @react-spring/native@9.2.4
npm WARN   node_modules/react-spring/node_modules/@react-spring/native
npm WARN
npm WARN Conflicting peer dependency: react@18.1.0
npm WARN node_modules/react
npm WARN   peer react@"18.1.0" from react-native@0.70.2
npm WARN   node_modules/react-native
npm WARN     peer react-native@">=0.58" from @react-spring/native@9.2.4
npm WARN     node_modules/react-spring/node_modules/@react-spring/native
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-swipeable-views@0.13.9
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"^16.8.0 || ^17" from @fluentui/react-component-event-listener@0.51.7
npm ERR!   node_modules/@fluentui/react-component-event-listener
npm ERR!     @fluentui/react-component-event-listener@"~0.51.6" from semantic-ui-react@2.0.3
npm ERR!     node_modules/semantic-ui-react
npm ERR!       semantic-ui-react@"^2.0.3" from the root project
npm ERR!   29 more (@fluentui/react-component-ref, @material-ui/core, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-swipeable-views@0.13.9
npm ERR! node_modules/react-swipeable-views
npm ERR!   react-swipeable-views@"^0.13.9" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^15.3.0 || ^16.0.0" from react-swipeable-views@0.13.9
npm ERR!   node_modules/react-swipeable-views
npm ERR!     react-swipeable-views@"^0.13.9" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: node v20.3.1, npm v9.7.2
* Operating system: Windows 10
* Environment setup and (python) version: v3.9.13

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
using the suggested --force or --legacy-peer-deps works but running `npm run build` also leads to a error

×  C:\RLI\github\oeplatform\oeo_viewer\client\node_modules\semantic-ui-css\semantic.min.css:undefined:undefined: Package subpath './2020/RequireObjectCoercible' is not defined by "exports" in C:\RLI\github\oeplatform\oeo_viewer\client\node_modules\es-abstract\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:259:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:589:9)
    at resolveExports (node:internal/modules/cjs/loader:571:36)
    at Module._findPath (node:internal/modules/cjs/loader:645:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1058:27)
    at Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (C:\RLI\github\oeplatform\oeo_viewer\client\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\RLI\github\oeplatform\oeo_viewer\client\node_modules\object.values\implementation.js:3:30)
