### ISSUE TITLE
Manual table creation

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#228]
There should be a "Create table" button in the schema list. The data types supported by sqlalchemy should be sufficient for column types.

**Comment by johannwagner** [comment]
Do we need an "Create Schema" button, too ? I cloned the latest dev branch, dunno if there is a button in other branches.

**Comment by johannwagner** [comment]
@MGlauer 

I ran into the following problem:
I create two arrays with content regarding columns and constraints and need to post them. 

It is not able to assign them to a value of a hidden input.
`<input id="array" name="array" value="">`
`document.getElementById('array').value = jsArray;`

I could create an ajax call, but I am not sure, how to pass the CSRF-Token. What would be the better way to go, if I don't want to expand the data structures to single hidden inputs ?

**Comment by johannwagner** [comment]
Nevermind, however headers are ignored, so you should send the csrfmiddlewaretoken with your data, which works quite fine. 

Solution: https://stackoverflow.com/questions/5100539/django-csrf-check-failing-with-an-ajax-post-request

**Comment by johannwagner** [comment]
@MGlauer 

I saw, that you completed the API. Should I use the API for table creation ?

**Comment by MGlauer** [comment]
@johannwagner Yes, this would be optimal, as this ensures, that the right table permissions are set automatically.

**Comment by johannwagner** [comment]
@MGlauer 

Did you changed the Table Creation API to allow multi column foreign keys ? If yes, how do I use this  ? If no, what should I do ?

**Comment by johannwagner** [comment]
@MGlauer ?

**Comment by MGlauer** [comment]
No, Schema creation is not required.

Am 29.09.2017 22:43 schrieb "Johann Wagner" <notifications@github.com>:

**Comment by johannwagner** [comment]
@MGlauer That was not the question. You read an old notification.

**Comment by MGlauer** [comment]
Ah sorry, I did not change it yet. Single foreign keys should be sufficient
for now.

Am 29.09.2017 23:22 schrieb "Johann Wagner" <notifications@github.com>:

@MGlauer <https://github.com/mglauer> That was not the question. You read
an old notification.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openego/oeplatform/issues/228#issuecomment-333242394>,
or mute the thread

**Comment by johannwagner** [comment]
@MGlauer I just added the request to the API.
How does the API support SQLAlchemy Datatypes ? Currently I am not able to use the API with SQL Alchemy data types.

**Comment by johannwagner** [comment]
Basic Data Types should work. I tested Integer and some other and they seems working, basically query looks good. I am not able to test it entirely, because I got different errors.

```
SQL STATEMENT: |CREATE TABLE grid."test" (test Integer  NOT NULL );| {}
Internal Server Error: /api/v0/schema/grid/tables/test/
Traceback (most recent call last):
  File "/home/vm/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vm/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/vm/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vm/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vm/.local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vm/.local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vm/.local/lib/python3.5/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/vm/.local/lib/python3.5/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vm/.local/lib/python3.5/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vm/git/oeplatform/api/views.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "/home/vm/git/oeplatform/api/views.py", line 177, in put
    holder=request.user)
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/vm/.local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'AnonymousUser'
```

**Comment by MGlauer** [comment]
This error raises, because you need to be logged in in order to create a table. I.e. we should hide the "Create table" button for anonymous users. 

This was the easy part. Here comes CSRF. Here be dragons. **Obviously**, the django rest framework uses different means to transfer the csrf-token for different request types. Because of course it does. This time the shamans determined that the X-CSRFToken header should be set for PUT requests - contrary to the `csrfmiddlewaretoken`-field used for POST-Requests.

**Comment by johannwagner** [comment]
Agreed.
And how do I authenticate against the server through the API ? CSRFToken ?

**Comment by MGlauer** [comment]
As the table creation should be part of the platform, your session-cookie should be sufficient. i.e. If you are logged in via your browser, the authentication should work automatically.

**Comment by johannwagner** [comment]
And how do I use endpoints that are not browsers ?

**Comment by MGlauer** [comment]
Each user has a [authtoken](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) that identifies him. The user-object is contained in each request an you can access the token via `request.user.token`if the user is non an instance of AnonymousUser
You can extend the header by `Authorization: Token <token>` to authenticate the user for a specific request.

**Comment by johannwagner** [comment]
Okay, so I just remove the button for AnonymusUser and reject all requests from unauthorized users. And at which point does CSRF-Token comes in ? Is it handled by Django automagically ?

**Comment by MGlauer** [comment]
Yes, only 'real' users should be able to create tables - maybe it would be more intuitive to redirect the user to the login page instead of just hiding the button. This can be done using the `@login_required`-decorator on your respective view-function.

CSRF-Tokens are handled by Django automatically (and as stated above not exactly in a deterministic fashion). Normally one could disable CSRF-Validation for an API, but as we are allowing Session-Authentication, this may cause a security issue.

**Comment by johannwagner** [comment]
@MGlauer Is it my task to fix the API at this point ? Right now, requests from anonymus users are not handled correctly and you will get the stacktrace from above.

**Comment by MGlauer** [comment]
No, i will fix this myself.

**Comment by christian-rli** [comment]
Before closing this issue, see if https://github.com/OpenEnergyPlatform/oeplatform/issues/133 has also been resolved. RequirementSpecificationID=13.

**Comment by MGlauer** [comment]
Closed due to the new upload wizard
